
name: Build document

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup typst
        uses: typst-community/setup-typst@v4

      - name: Grab dissertation template
        run: |
          mkdir -p ~/.local/share/typst/packages/local/dissertation
          git clone https://github.com/nleroy917/dissertation-typst-template.git ~/.local/share/typst/packages/local/dissertation

      - name: Fetch references
        run: |
          curl -H "Authorization: token {{ secrets.GH.PAT }}" \
          -H "Accept: application/vnd.github.v3.raw" \
          -L -o refs.bib \
          "https://api.github.com/repos/nleroy917/references/contents/refs.bib"

      - name: Build document
        run: |
          typst compile main.typ main.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} â€” ${{ env.DATE }}"
          files: main.pdf


      