
name: Build document

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup typst
        uses: typst-community/setup-typst@v4

      - name: Grab dissertation template
        run: |
          mkdir -p ~/.local/share/typst/packages/local/dissertation
          git clone https://github.com/nleroy917/dissertation-typst-template.git ~/.local/share/typst/packages/local/dissertation

      - name: Fetch references
        run: |
          rm -f refs.bib
          curl "https://raw.githubusercontent.com/nleroy917/references/refs/heads/master/refs.bib" -o refs.bib --create-dirs

      - name: Build document
        run: |
          typst compile main.typ main.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} â€” ${{ env.DATE }}"
          files: main.pdf
      
      - name: Create index
        run: |
          mkdir public
          cp main.pdf public/
          echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Document Build</title></head><body><h1>Document Build</h1><ul><li><a href='main.pdf'>Download PDF</a></li></ul></body></html>" > public/index.html
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: public/
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
